mysite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('results/<int:question_id>/', views.results, name="results")
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("blog/", include("blog.urls")),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    # path("", views.index, name="index"),
    path("", views.IndexView.as_view(), name="index"),
    # ex: /polls/4
    # path("<int:question_id>", views.detail, name="detail"),
    # the 'name' value as called by the {% url %} template tag
    # path("<int:question_id>/", views.detail, name="detail"),
    # added the word 'specifics'
    # path("specifics/<int:question_id>/", views.detail, name="detail"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    # ex: /polls/4/results
    # path("<int:question_id>/results", views.results, name="results"),
    path("<int:pk>/results", views.ResultsView.as_view(), name="results"),
    # ex: /polls/4/vote
    path("<int:question_id>/vote", views.vote, name="vote"),
]

mysite/blog/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length = 200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days = 1)

class Choice(models.Model):

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length = 200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length = 200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days = 1)

class Choice(models.Model):

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length = 200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/blog/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.conf import settings
from .models import Question
from django.template import loader

# Create your views here.

def stopItr(name):
    raise StopIteration

def home(request = HttpRequest):
    flag_middleware = ''
    # print([ value for middleware in settings.MIDDLEWARE for value in middleware.split('.')])
    for middleware in settings.MIDDLEWARE:
        middlewareNames = middleware.split('.')
        for name in middlewareNames:
            if name == 'AuthenticationMiddleware':
                flag_middleware = middleware
                break
    return HttpResponse("<h2>Vote Home page - %s </h2" % flag_middleware)

def about(request = HttpRequest):
    id = 6
    context = {
        "id": id
    }
    return render(request, 'blog/about.html', context)

def results(request = HttpRequest, question_id = None):
    question = ['Who is working?', 'How do you do?', 'What is use case?']
    context = {
        "heading": "Select Question",
        "question_list": question
    }
    return render(request, 'blog/results.html', context)

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic

from .models import Question, Choice

# Create your views here.

# def index(request):
#     latest_question_list = Question.objects.order_by("-pub_date")[:5]
#     # template = loader.get_template('polls/index.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     # return HttpResponse(template.render(context, request))
#     return render(request, 'polls/index.html', context)

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

# def detail(request, question_id):
#     # try:
#     #     question = Question.objects.get(pk = question_id)
#     #     context = {
#     #         'question': question
#     #     }
#     # except Question.DoesNotExist:
#     #     raise Http404('Question does not exist')

#     question = get_object_or_404(Question, pk = question_id)
#     context = {
#         'question': question
#     }

#     return render(request, 'polls/detail.html', context)

#     # return HttpResponse("<h2>You're looking at question number <i>{}</i>.</h2>".format(question_id))

class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

# def results(request, question_id):
#     # return HttpResponse("<h2>You're looking at the result of question number <i>%s</i>." % question_id)
#     question = get_object_or_404(Question, pk=question_id)
#     context = {
#         'question': question
#     }

#     return render(request, 'polls/results.html', context)

class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

def vote(request, question_id):
    # response = "<h2>You're voting on question <i>%s</i></h2>"
    # return HttpResponse(response % question.id)
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice!"
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block title %} About {% endblock %}
{% block content %}
<a href="{% url 'blog:results' id %}" class="btn btn-primary">About</a>
{% endblock %}

mysite/blog/templates/blog/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title%}My Blog{% endblock %}</title>
  </head>
  <body>
    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

mysite/blog/templates/blog/home.html
<h2>Hello Home</h2>

mysite/blog/templates/blog/results.html
{% extends 'blog/base.html' %}
{% block title %} Results {% endblock %}
{% block content %}
<form method="POST" action="{% url 'blog:about' %}">
    {% csrf_token %}
    <ul class="list-group list-group-flush">
        {% for name in question_list %}
        <li class="list-group-item {% if forloop.counter == 2 %} active {% endif %}">{{name}}</li>
        {% endfor %}
      </ul>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p style="color: brown;"><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="POST">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}"
        value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text}}</label><br>
    {% endfor %}
    <div style="margin-top: 10px;">
        <input type="submit" value="Vote">
    </div>
</form>

mysite/polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" >
<link rel="stylesheet" type="text/css" href="{% static 'polls/polls.css' %}" >
{% if latest_question_list %}
    <div>
        <img src="{% static 'polls/images/logo2.png' '%}" />
    </div>
    <ul>
    {% for question in latest_question_list %}
        <!-- <li><a href="/polls/{{ question.id }}">{{ question.question_text }}</a></li> -->
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/results.html
<div>
    <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }}  vote{{ choice.votes | pluralize}}</li>
        {% endfor %}
    </ul>
    <br />
    <a href="{% url 'polls:detail' question.id %}">Vote Again?</a>
</div>